version: '3.1'

services:
  app:
    image: docker.pkg.github.com/v1ack/fu-calendar/calendar  # Адрес Docker хранилища
    expose:  # Открытый порт
      - 4040
    ports:
      - "4040:4040"
    environment:  # Переменные окружения
      APP_API_ADDRESS: 0.0.0.0
      API_FILES_FOLDER: /mnt/files
      CACHE_TYPE: redis  # Тип кеша (redis, file или no)
      REDIS_URL: redis://redis/0  # Адрес Redis

  redis:
    image: redis  # Образ
    command: ["redis-server", "--appendonly", "yes"]  # Команда запуска
    expose:  # Порт, если нужен для доступа извне
      - 6379
    ports:
      - 6379:6379
