version: '3.1'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
#    command: python3 /mnt/start.py
    volumes:
      - .:/mnt
      - ./ics_folder:/mnt/ics_folder
    working_dir: /mnt/
    expose:
      - 4040
    ports:
      - "4040:4040"
    environment:
      APP_API_URL: 0.0.0.0
      APP_REDIS: redis://redis/0

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - 6379
    ports:
      - 6379:6379
